name: CI to Docker Hub

on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-debug:latest

      - name: Touch file
        run: touch empty

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
